server.port: 9080

spring:
  application:
    name: string-producer-service

simulation.sleep: 3000

kafka:
  bootstrap-servers: localhost:29092
  producer:
    topic: string-serialization-news
    num-partitions: 4