server.port: 9080

spring:
  application:
    name: string-producer-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        topic: string-serialization-news
        num-partitions: 4

simulation.sleep: 3000
