server.port: 9083

spring:
  application:
    name: json-consumer-service

kafka:
  bootstrap-servers: localhost:29092
  consumer:
    group-id: json-consumer-service-group
    auto-offset-reset: earliest
    topic: json-serialization-news