server.port: 9082

spring:
  application:
    name: json-producer-service

simulation.sleep: 3000

kafka:
  bootstrap-servers: localhost:29092
  producer:
    topic: json-serialization-news
    num-partitions: 4