server.port: 9082

spring:
  application:
    name: json-producer-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        topic: json-serialization-news
        num-partitions: 4

simulation.sleep: 3000
