server.port: 9085

spring:
  application:
    name: avro-consumer-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: avro-consumer-service-group
      topic: avro-serialization-news
      auto-offset-reset: earliest
    listener:
      concurrency: 2