server.port: 9080

spring:
  application:
    name: avro-3-producer-service

simulation.sleep: 3000

kafka:
  bootstrap-servers: localhost:29092
  schema-registry-url: http://localhost:8081
  producer:
    topic: avro-3-serialization-news
    num-partitions: 4